refactor: mario issue-1의 로직 수정 및 반영
Monkey-2G/owenLaravelUp pull request #9
Opened 2021-11-24 00:11 UTC by Monkey-2G

1. DB 트랜잭션 자동으로 처리 변경 및 repository로 위치 변경

2. try~catch 문에서 catch에 걸릴 시, new가 아닌 기존 exception으로 사용 변경

3. repository에서 return 값 fresh(); 제거

4. save() Method DB 트랜잭션 및 로그 적용

5. selectById POST에서 GET 방식으로 변경

2021-11-24 02:37 UTC, dhtmdgkr123 requested changes
@Monkey-2G 리뷰사항 확인 부탁드립니다!

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Repositories/UserRepository.php
> +            $user = new $this->user;
@Monkey-2G 변수명을 인스턴스로 생성하는 패턴 말고 클래스 네임을 직접 기입하거나 해당 인스턴스를 사용하는걸 추천합니다. 왜 새당 로직이 나왓는지 궁금해용!

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Repositories/UserRepository.php
> +            $user->password = Crypt::encryptString($data['password']);
@Monkey-2G 뮤테이터 사용을 권장 드립니다 (https://laravel.kr/docs/8.x/eloquent-mutators)

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Repositories/UserRepository.php
> +            }
@Monkey-2G  try, catch로 감싼 이유가 있나요? 해당 사유 궁금합니다.

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Repositories/UserRepository.php
> +            }
@Monkey-2G 저는 해당상황에서는 아차피 단일 커넥션이라서 내부에서 처리를 하기 때문에 트랜잭션 결과값을 가지고 throw 를 판단합니다.

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Repositories/UserRepository.php
> +            }
@Monkey-2G 이부분도 해당상황에서는 아차피 단일 커넥션이라서 내부에서 처리를 하기 때문에 트랜잭션 결과값을 가지고 throw 를 판단합니다.

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Services/UserService.php
> +        }
@Monkey-2G 
익셉션 핸들러를 통해보는건 어떨까요? https://laravel.kr/docs/8.x/errors#Exception%20%ED%95%B8%EB%93%A4%EB%9F%AC

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Services/UserService.php
>          }
@Monkey-2G 
익셉션 핸들러를 통해보는건 어떨까요? https://laravel.kr/docs/8.x/errors#Exception%20%ED%95%B8%EB%93%A4%EB%9F%AC

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Services/UserService.php
> +        }
@Monkey-2G
익셉션 핸들러를 통해보는건 어떨까요? https://laravel.kr/docs/8.x/errors#Exception%20%ED%95%B8%EB%93%A4%EB%9F%AC

2021-11-24 02:37 UTC, dhtmdgkr123 commented on routes/api.php
> +    Route::get('selectById', [UserController::class, 'selectById']);
@Monkey-2G  REST 규약을 다시 확인하고 올바른 메소드를 사용해주세요

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
>          }
@Monkey-2G 아부분도 익셉션 핸들러로 빼는걸 권장합니다.

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
>          }
@Monkey-2G 아부분도 익셉션 핸들러로 빼는걸 권장합니다.

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
@Monkey-2G 아부분도 익셉션 핸들러로 빼는걸 권장합니다.

2021-11-24 02:37 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
>          return response()->json($result);
@Monkey-2G 아부분도 익셉션 핸들러로 빼는걸 권장합니다.

2021-11-24 02:40 UTC, dhtmdgkr123 commented
@Monkey-2G 풀 코드리뷰는 데브 브랜치에서 진행하겠습니다.

2021-11-24 02:49 UTC, dhtmdgkr123 commented
@Monkey-2G 질문
1. 서비스레이어란?
    1.1 왜쓰나요? 
2. 리포지토리 레이어란?
    2. 1 왜쓰나요?

2021-11-25 16:25 UTC, Monkey-2G commented
@dhtmdgkr123 

1. 서비스 레이어 : 여러개의 도메인 모델을 필요한 데이터로 가공 및 취합하여 제공하는 계층.
 -> 하나의 도메인 모델에서 모든 것을 처리하게 되면, 해당 모델에 대한 책임이 너무 많이 가게 되고,
    책임이 많이 가게 된다는 것은 코드 유지보수에 대한 어려움이 있기때문에, 이러한 분산 및 처리를 해줄 계층이 필요하기 때문이라 생각합니다.

2. 리포지토리 레이어 : 저장소를 추상화하여 각기 다른 요청의 데이터가 와도 일관된 방식으로 데이터 처리를 할 수 있는 계층.
 -> 도메인 모델과 데이터베이스를 분리 (책임 분할)하기 위함이라고 생각합니다.

2021-11-25 16:33 UTC, Monkey-2G commented on app/Repositories/UserRepository.php
> +            $user = new $this->user;
new User();와 $this->user; 두 가지 방법이 짬뽕이 된 것 같네요 ^^;

2021-11-25 16:36 UTC, Monkey-2G commented on app/Repositories/UserRepository.php
> +            }
설명해주신 내용을 읽어보니 try~catch 안에 트랜잭션이 들어가야한다는 말로 이해가 됩니다.

2021-11-25 16:41 UTC, Monkey-2G commented on app/Repositories/UserRepository.php
> +            }
말씀해주신것을 이해하기로는 try~catch문 안에 트랜잭션 수행이 이루어진다라고 이해하였습니다.

2021-11-26 14:53 UTC, dhtmdgkr123 commented on app/Repositories/UserRepository.php
> +            }
@Monkey-2G 익셉션을 throw를 할 때 왜 새로운 익셉션을 throw한 것에 대한 질문이였어용~! 
안에서 이루어지는것은 안에서 이루어 지는 것 인데 다만 try catch가 왜 들어갓는지 그 익셉션을 왜 새로운 인스턴스로 던졋는지 그겟어 데한 사유가 궁금햇었습니다!
개인적으로 저는 익셉션 핸들러로 throw하는 방향을 추천합니다. 한곳에서 익셉션을 핸들하면 나중에 익셉션 throw 시 원하는 response를 뱉을 수 있기 때문에 더 좋습니다!

2021-11-26 15:03 UTC, dhtmdgkr123 commented
> @dhtmdgkr123
> 
> 1. 서비스 레이어 : 여러개의 도메인 모델을 필요한 데이터로 가공 및 취합하여 제공하는 계층.
>    -> 하나의 도메인 모델에서 모든 것을 처리하게 되면, 해당 모델에 대한 책임이 너무 많이 가게 되고,
>    책임이 많이 가게 된다는 것은 코드 유지보수에 대한 어려움이 있기때문에, 이러한 분산 및 처리를 해줄 계층이 필요하기 때문이라 생각합니다.
> 2. 리포지토리 레이어 : 저장소를 추상화하여 각기 다른 요청의 데이터가 와도 일관된 방식으로 데이터 처리를 할 수 있는 계층.
>    -> 도메인 모델과 데이터베이스를 분리 (책임 분할)하기 위함이라고 생각합니다.

아주 좋습니다!
첨언을 하자면 서비스레이어는 위에서 언급한 비즈니스 계층을 수행하는 레이어 이며 같은 계층끼리 DI를 한다거나 의존하는 경우 circular dependency 가 발생하여 계층구조가 명확해지지 않는  디자인이 나와 좋지 않아 저는 선호하지 않는편 입니다!

2021-12-08 00:39 UTC, dhtmdgkr123 requested changes
@Monkey-2G Try, catch에 대한 사유를 다시한번 생각해보고 핸들어에 대한 생각을다시 해봅시당~

2021-12-08 00:39 UTC, dhtmdgkr123 commented on app/Models/User.php
> +    }
@Monkey-2G 굳굳굳 좋아용 그런데 이건 저도 몰라서 그러는건데 
```php
Crypt::encryptString($value); # 이놈이랑
bcrypt($value); # 이놈이랑  다른게 잇을까요?
```

2021-12-08 00:39 UTC, dhtmdgkr123 commented on routes/api.php
> +    Route::get('selectById/{id}', [UserController::class, 'selectById']);
@Monkey-2G 리퀘스트 패스에 update나 delete나 selectById가 필요할까요?

2021-12-08 00:39 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
> +        } catch (Throwable $e) {
@Monkey-2G 그렇지만 try ,catch사용의 근본적인 사유,,,

2021-12-08 01:08 UTC, dhtmdgkr123 commented on routes/api.php
> +    Route::get('selectById/{id}', [UserController::class, 'selectById']);
@Monkey-2G 행위는 URL에 포함하지 않습니다.

2021-12-08 01:12 UTC, dhtmdgkr123 commented on app/Models/User.php
> +    }
@Monkey-2G 파라미터 타입힌트 여부 확인 및 적용 부탁드립니다.

2021-12-09 00:09 UTC, dhtmdgkr123 approved these changes
@Monkey-2G 
코드 확인 완료 했습니다. 코멘트 확인 부탁드립니다.

2021-12-09 00:09 UTC, dhtmdgkr123 commented on app/Repositories/UserRepository.php
> +            $user->update();
@Monkey-2G 굳굳굳! 아주 좋아요 하지만 조금 더 간결한 코드를 보여드리고 싶습니다.
권장사항은 아니고 그냥 참고사항입니다.

```php
/**
 * updateOrFail메소드로 트랜잭션 및 업데이트가 동작됩니다!
 */
$this->getUserById($data)->updateOrFail($data);
```

2021-12-09 00:09 UTC, dhtmdgkr123 commented on app/Repositories/UserRepository.php
> +            $user->delete();
@Monkey-2G 
얘도 마찬가지 입니다
```php
/**
 * updateOrFail메소드로 트랜잭션 및 딜리트가 동작됩니다!
 */
$this->getUserById($data)->deleteOrFail($data);
```

2021-12-09 00:12 UTC, dhtmdgkr123 commented
@Monkey-2G 그리고 번외로
```php
/**
 * PK인 id 값으로 user 조회
 * @param array $data (id)
 * @return User
 */
public function getUserById(array $data) : User
{
    return User::findOrFail($data['id']);
}
```
해당 메소드에소 파라미터에 키가 id가 없을경우 장애가 발생예상 됩니다. 그러하여 이부분을 id(int)만 따로 받도록 하는건 어떨까요?

2021-12-09 15:53 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
>          }
@Monkey-2G 추후 미들웨어로 리스폰스 인터셉터 구현 과제로 두겠습니다!

2021-12-09 15:53 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
>          }
@Monkey-2G 추후 미들웨어로 리스폰스 인터셉터 구현 과제로 두겠습니다!

2021-12-09 15:54 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
>          return response()->json($result);
@Monkey-2G 추후 미들웨어로 리스폰스 인터셉터 구현 과제로 두겠습니다!

2021-12-10 02:33 UTC, dhtmdgkr123 approved these changes
@Monkey-2G 
잘 만들어주셨습니다. 저도 만족하는 코드가 나왓습니다! 굳굳굳
하지만 아주 약간 아쉬운 부분, try, catch 및 핸들러에서 처리가 아쉬웟습니다. 해당부분은 issue오픈하고 피처 구현 스텝으로 넙어가겠습니다.
머지 바랍니다.

2021-12-10 02:33 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
>          }
@Monkey-2G 참고로 해당 컨트롤러에서 try catch를 사용하고 잇기 때문에 핸들러까지 타지 않을꺼로 보여집니다.
추후 handler 적용을 목표료 해당 부분은 Issue 오픈하겠습니다.

2021-12-10 02:33 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
>          }
@Monkey-2G 여기도 동일하게 해당 컨트롤러에서 try catch를 사용하고 잇기 때문에 핸들러까지 타지 않을꺼로 보여집니다.
추후 handler 적용을 목표료 해당 부분은 Issue 오픈하겠습니다.

2021-12-10 02:33 UTC, dhtmdgkr123 commented on app/Http/Controllers/UserController.php
> +                'error' => $e->getFile().'/'.$e->getLine().' / '.$e->getMessage()
@Monkey-2G 여기도 동일하게 해당 컨트롤러에서 try catch를 사용하고 잇기 때문에 핸들러까지 타지 않을꺼로 보여집니다.
추후 handler 적용을 목표료 해당 부분은 Issue 오픈하겠습니다.

2021-12-15 01:49 UTC, dhtmdgkr123 requested changes
@Monkey-2G 코멘트 확인 후 답변요청드린 부분 확인 부탁드립니다.

2021-12-15 01:49 UTC, dhtmdgkr123 commented on app/Exceptions/Handler.php
> +        });
@Monkey-2G 클로저 타입힌트 빠졌습니다.

2021-12-15 01:49 UTC, dhtmdgkr123 commented on app/Exceptions/Handler.php
> +    public function customException(Throwable $e, Request $request)
@Monkey-2G 리턴 타입 힌트 빠졋습니다.

2021-12-15 01:49 UTC, dhtmdgkr123 commented on app/Exceptions/Handler.php
> +        return response('Exception Handleing Test', 444);
@Monkey-2G 444는 응답없음으로 일부러 상태를 표현한것 인가요?

2021-12-15 01:49 UTC, dhtmdgkr123 commented on app/Exceptions/Handler.php
> +    public function customException(Throwable $e, Request $request)
@Monkey-2G 옷 그리구 이 메소드의 네이밍이 왜 커스텀 익셉션인지 조금 궁금해용~!

2021-12-15 14:15 UTC, Monkey-2G commented on app/Exceptions/Handler.php
> +    public function customException(Throwable $e, Request $request)
@dhtmdgkr123 
처음엔 userCRUDException으로 명명하려다가, 나중엔 user에 대한 error handling 말고도 다른 처리를 해당 함수 안에서 처리해야 할 것 같아서 customException으로 명명했습니다.

2021-12-15 14:15 UTC, Monkey-2G commented on app/Exceptions/Handler.php
> +        return response('Exception Handleing Test', 444);
@dhtmdgkr123 404 응답으로 처리하려고 했는데, 오타가 났네요 ^^;

2021-12-15 14:16 UTC, Monkey-2G commented on app/Exceptions/Handler.php
> +        });
@dhtmdgkr123 
반영하겠습니다.

2021-12-16 05:36 UTC, dhtmdgkr123 requested changes
@Monkey-2G 코멘트 확인해주세요~

2021-12-16 05:36 UTC, dhtmdgkr123 commented on app/Exceptions/Handler.php
> +        return response('Exception Handleing Test', 404);
@Monkey-2G 
```php
\Illuminate\Http\Response::HTTP_NOT_FOUND
```
위와 같이 상수처리 해보는건 어떨까요?
그리고 현재 TODO관련한건 제가 구현 예제를 PR 오픈해보겠습니다~

2021-12-16 14:29 UTC, Monkey-2G commented on app/Exceptions/Handler.php
> +        return response('Exception Handleing Test', 404);
@dhtmdgkr123 
기본 제공하는 상수로 변경했습니다. 다음부터는 vendor 쪽에서 무엇을 제공하는지도 한 번 씩 봐야겠습니다 :)

2021-12-16 14:32 UTC, dhtmdgkr123 approved these changes
@Monkey-2G 머지 요청합니다 전체코드 approve합니다.

2021-12-16 15:14 UTC, merged